version: 0.2

env:
  variables:
    hugo_version: "0.63.2"

phases:
  install:
    runtime-versions:
      docker: 18
      golang: 1.13
    commands:
      - wget "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.deb"
      - dpkg -i hugo_${hugo_version}_Linux-64bit.deb
    finally:
      - hugo version
  build:
    commands:
      - hugo
      - hugo deploy --maxDeletes -1
    finally:
      - echo "Script finished running"