version: 0.2

env:
  variables:
    hugo_version: "0.63.2"

phases:
  install:
    runtime-versions:
      golang: 1.13
    commands:
      - wget "https://github.com/gohugoio/hugo/releases/download/v${hugo_version}/hugo_${hugo_version}_Linux-64bit.deb"
      - dpkg -i hugo_${hugo_version}_Linux-64bit.deb
    finally:
      - hugo version
  build:
    commands:
      - cd public
      - aws s3 sync . s3://www.gonzague.dev/
    finally:
      - echo "Script finished running"