baseURL = "https://www.gonzague.dev/"
languageCode = "fr-FR"
title = "Gonzague"
theme = "hyde"
uglyurls = true
googleAnalytics = "UA-158620326-1"

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/hessu1337/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/gonzague-pagin-609834a7/"}
  ]

[params]
  description = "My personal blog where I present my work and stuff"
  themeColor = "theme-base-0d"