baseURL = "https://d1t6kr0yfdny60.cloudfront.net/"
languageCode = "fr-FR"
title = "Gonzague"
theme = "hyde"
uglyurls = true

[Menus]
  main = [
      {Name = "Github", URL = "https://github.com/hessu1337/"},
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/gonzague-pagin-609834a7/"}
  ]

[params]
  description = "My personal blog where I present my work and stuff"

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "s3deployment"
URL = "s3://blog.gonzague.pagin?region=eu-west-3"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true